# Generated by Django 3.2.8 on 2021-10-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steveharrington', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ecosystemcharacteristicsterms',
            options={'verbose_name': 'ecosystem term info', 'verbose_name_plural': 'ecosystem terms info'},
        ),
        migrations.AlterModelOptions(
            name='ecosystempotentials',
            options={'verbose_name': 'ecosystem potential info', 'verbose_name_plural': 'ecosystem potentials info'},
        ),
        migrations.AlterModelOptions(
            name='ecosystemprojects',
            options={'verbose_name': 'ecosystem project info', 'verbose_name_plural': 'ecosystem projects info'},
        ),
        migrations.AddField(
            model_name='ecosystemcharacteristicsterms',
            name='index',
            field=models.IntegerField(default=0, verbose_name='index'),
        ),
        migrations.AddConstraint(
            model_name='ecosystemcharacteristicsterms',
            constraint=models.UniqueConstraint(fields=('ecosystem', 'characteristic', 'index'), include=('term',), name='unique_term_info'),
        ),
        migrations.AddConstraint(
            model_name='ecosystempotentials',
            constraint=models.UniqueConstraint(fields=('ecosystem', 'potential', 'characteristic'), include=('characteristic',), name='unique_potential_info'),
        ),
        migrations.AddConstraint(
            model_name='ecosystemprojects',
            constraint=models.UniqueConstraint(fields=('ecosystem', 'project', 'characteristic', 'rank'), name='unique_project_info'),
        ),
    ]
